// data/spaces.ts
import type { Space } from "@/lib/types"

export const staticSpaces: Space[] = [
  {
    id: "space-1",
    name: "Digital Design Studio",
    subtitle: "Advanced design workspace with cutting-edge tools",
    description: "A comprehensive learning environment for digital design professionals...",
    colorPalette: ["#6366f1", "#8b5cf6"] as [string, string],
    size: 120,
    price: 299,
    isActive: true,
    keyPoints: ["3D Printing", "VR Setup", "Laser Cutting", "AI Design Tools"],
    instructor: {
      id: "i1",
      name: "Sarah Johnson",
      role: "Lead Designer",
      avatar: "https://github.com/shadcn.png",
      cvUrl: "/cv/sarah.pdf",
    },
    students: [
      { id: "s1", name: "Alex Chen", avatar: "https://github.com/shadcn.png" },
      { id: "s2", name: "Maria Gomez", avatar: "https://github.com/shadcn.png" },
      { id: "s1", name: "Alex Chen", avatar: "https://github.com/shadcn.png" },
      { id: "s2", name: "Maria Gomez", avatar: "https://github.com/shadcn.png" },
      { id: "s1", name: "Alex Chen", avatar: "https://github.com/shadcn.png" },
      { id: "s2", name: "Maria Gomez", avatar: "https://github.com/shadcn.png" },
    ],
    createdAt: "2024-01-15",
    tags: ["Design", "Technology"],
    schedule: ["Mon 10:00 AM", "Wed 2:00 PM"],
    completedModules: 4,
    totalModules: 6,
    partner: "Creative Tech Inc.",
    partnerLogo: "/logos/creative-tech.svg",
    rating: 4.7,
    certifications: ["3D Design Expert", "VR Certified", "AI Design Specialist"],
  },
  {
    id: "space-2",
    name: "Code Lab Pro",
    subtitle: "Professional coding environment with CI/CD pipelines",
    description: "Advanced programming space featuring real-world project simulations...",
    colorPalette: ["#10b981", "#059669"] as [string, string],
    size: 90,
    price: 199,
    isActive: false,
    keyPoints: ["Pair Programming", "Code Review", "CI/CD", "Cloud Integration"],
    instructor: {
      id: "i2",
      name: "Mike Chen",
      role: "Senior Developer",
      avatar: "https://github.com/shadcn.png",
      cvUrl: "/cv/mike.pdf",
    },
    students: [{ id: "s3", name: "John Doe", avatar: "https://github.com/shadcn.png" }],
    createdAt: "2024-02-01",
    tags: ["Programming", "DevOps"],
    schedule: ["Tue 9:00", "Thu 3:00"],
    completedModules: 2,
    totalModules: 5,
    rating: 4.2,
    certifications: ["Full Stack Developer", "Cloud Engineer"],
  },
]
